# SECRET_KEY="django-insecure-rq&-hsne!!t#ice*&9g9$5b*#@dyv4r+w!i@7t@4g96901!$t6"
SECRET_KEY: "5-3igy09w4mxqw7pe*sa8)uf^$o!ysc1l&ww4*gy*h3vwy(ww-"
DB_NAME: "ulmus"
DB_USER: "admin"
DB_PASSWORD: "root"
DB_HOST: "127.0.0.1"
DB_PORT: "5433"
