# Generated by Django 5.0.6 on 2024-06-26 15:02

import base.helpers
import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0035_auto_20230822_2208'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsListItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('text', models.CharField(max_length=255, verbose_name='List Item')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='AboutUsSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('description_1', models.TextField(blank=True, null=True, verbose_name='Description 1')),
                ('description_2', models.TextField(blank=True, null=True, verbose_name='Description 2')),
                ('description_3', models.TextField(blank=True, null=True, verbose_name='Description 3')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('subject', models.CharField(max_length=256, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact Request',
                'verbose_name_plural': 'Contact Requests',
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('description', models.TextField(verbose_name='Description')),
                ('company_address', models.CharField(max_length=256, verbose_name='Addresse de la société')),
                ('company_email', models.EmailField(max_length=254, verbose_name='E-mail de la société')),
                ('company_phone_number', models.CharField(max_length=32, verbose_name='Numéro téléphone de la société')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FeatureElement',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('icon_class', models.CharField(help_text="Enter a CSS class for the icon (e.g., 'bi bi-heart')", max_length=50, verbose_name='Icon CSS Class')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon_class', models.CharField(help_text="Enter a CSS class for the icon (e.g., 'bi bi-heart')", max_length=50, verbose_name='Icon CSS Class')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CounterSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=125, verbose_name='Titre')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
                ('clients_max_counter', models.IntegerField(verbose_name='Compteur clients')),
                ('projects_max_counter', models.IntegerField(verbose_name='Compteur projets')),
                ('workers_max_counter', models.IntegerField(verbose_name='Compteur employés')),
                ('background_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_section_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Image de fond')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('header', models.CharField(max_length=125, verbose_name='Titre')),
                ('text', models.TextField(verbose_name='Description')),
                ('button_text', models.CharField(max_length=125, verbose_name='Texte Bouton')),
                ('button_link', models.CharField(blank=True, choices=base.helpers.get_page_url_choices, max_length=256, verbose_name='Lien Bouton')),
                ('background_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cta_section_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Image de fond')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FeaturesSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('features_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features_section_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Image de section caractéristiques')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Sous-titre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('background_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_section_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Image de fond')),
            ],
            options={
                'get_latest_by': 'created_at',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='base.service')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
