# Generated by Django 5.0.6 on 2024-06-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_herosection_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='plugins/hero_section/', verbose_name='Image de fond'),
        ),
    ]
