# Generated by Django 5.0.6 on 2024-06-24 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_herosection_background_image'),
        ('cms', '0035_auto_20230822_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('description_1', models.TextField(blank=True, null=True, verbose_name='Description 1')),
                ('description_2', models.TextField(blank=True, null=True, verbose_name='Description 2')),
                ('description_3', models.TextField(blank=True, null=True, verbose_name='Description 3')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='AboutUsListItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('text', models.CharField(max_length=255, verbose_name='List Item')),
                ('about_us_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='base.aboutussection')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
