# Generated by Django 5.0.6 on 2024-06-24 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_aboutussection_aboutuslistitem'),
        ('cms', '0035_auto_20230822_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon_class', models.CharField(help_text="Enter a CSS class for the icon (e.g., 'bi bi-heart')", max_length=50, verbose_name='Icon CSS Class')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='base.service')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
