# Generated by Django 5.0.6 on 2024-06-24 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_service_servicessection_servicecard'),
        ('cms', '0035_auto_20230822_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('header', models.CharField(max_length=125, verbose_name='Titre')),
                ('text', models.TextField(verbose_name='Description')),
                ('button_text', models.CharField(max_length=125, verbose_name='Texte Bouton')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
