# Generated by Django 5.0.6 on 2024-06-24 14:37

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_ctasection'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ctasection',
            name='background_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cta_section_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Image de fond'),
        ),
    ]
