# Generated by Django 5.0.6 on 2024-06-24 15:06

import base.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_ctasection_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctasection',
            name='button_link',
            field=models.CharField(blank=True, choices=base.helpers.get_page_url_choices, max_length=256, verbose_name='Lien Bouton'),
        ),
    ]
