# Generated by Django 5.0.6 on 2024-06-24 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_ctasection_button_link'),
        ('cms', '0035_auto_20230822_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('description', models.TextField(verbose_name='Description')),
                ('company_address', models.CharField(max_length=256, verbose_name='Addresse de la société')),
                ('company_email', models.EmailField(max_length=254, verbose_name='E-mail de la société')),
                ('company_phone_number', models.CharField(max_length=32, verbose_name='Numéro téléphone de la société')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
