# Generated by Django 5.0.6 on 2024-06-25 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_contactrequest'),
        ('cms', '0035_auto_20230822_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=125, verbose_name='Titre')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
                ('clients_max_counter', models.IntegerField(verbose_name='Compteur clients')),
                ('projects_max_counter', models.IntegerField(verbose_name='Compteur projets')),
                ('workers_max_counter', models.IntegerField(verbose_name='Compteur employés')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
