# Generated by Django 5.0.6 on 2024-06-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_herosection_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutuslistitem',
            name='about_us_section',
        ),
    ]
