# Generated by Django 5.0.6 on 2024-06-25 10:06

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_aboutuslistitem_about_us_section'),
        ('cms', '0035_auto_20230822_2208'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureElement',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('icon_class', models.CharField(help_text="Enter a CSS class for the icon (e.g., 'bi bi-heart')", max_length=50, verbose_name='Icon CSS Class')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FeaturesSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('features_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features_section_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Image de section caractéristiques')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
